using UnityEditor;
using UnityEngine;

/// <summary>
/// One-shot fix for UniDragAndDropForMac.bundle: its .meta file was
/// generated by a very old Unity version using the pre-2018 per-OS
/// "Standalone: OSXUniversal" plugin importer schema, which the
/// modern unified Standalone build target silently ignores - the
/// native bundle was being left out of Standalone builds entirely.
/// This rewrites the settings via Unity's own importer API so the
/// resulting .meta is guaranteed valid for this Editor version.
/// </summary>
public static class FixUniDragAndDropImportSettings
{
    private const string BundlePath =
        "Assets/UniDragAndDrop/Plugins/macOS/UniDragAndDrop.bundle";

    [MenuItem("Tools/Fix UniDragAndDrop Plugin Import Settings")]
    public static void Fix()
    {
        PluginImporter importer =
            AssetImporter.GetAtPath(BundlePath) as PluginImporter;

        if (importer == null)
        {
            Debug.LogError(
                $"Could not find a PluginImporter at: {BundlePath}"
            );

            return;
        }

        importer.SetCompatibleWithEditor(true);
        importer.SetEditorData("OS", "OSX");
        importer.SetEditorData("CPU", "AnyCPU");

        importer.SetCompatibleWithAnyPlatform(false);
        importer.SetCompatibleWithPlatform(BuildTarget.StandaloneOSX, true);
        importer.SetPlatformData(BuildTarget.StandaloneOSX, "CPU", "AnyCPU");

        importer.SaveAndReimport();

        Debug.Log(
            "UniDragAndDrop.bundle import settings fixed for " +
            "StandaloneOSX. Rebuild the app now."
        );
    }
}
